version: "3.4"
services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
     - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin

  # PG POOL
  pg-pool:
    build:
      context: ./
      dockerfile: pgpool.dockerfile
    environment:
      TZ: 'America/Fortaleza'
    volumes:
      - ./pgpool-conf:/etc/pgpool-II/
    ports:
      - "9999:9999"
    tty: true

  # MASTER
  pg-master:
    image: postgres:9.4
    environment:
      TZ: 'America/Fortaleza'
    volumes:
     - dados-pg-master:/var/lib/postgresql/data

  # SLAVE
  pg-slave:
    image: postgres:9.4
    environment:
      TZ: 'America/Fortaleza'
    volumes:
     - dados-pg-slave:/var/lib/postgresql/data

volumes:
 dados-pg-master:
 dados-pg-slave:
